### ISSUE TITLE
version problems

### ISSUE THREAD

**Issue by jiangyanjavawin** [ace19-dev/mvcnn-tf#3]
when i am trying run the code,i faced some problems:
Traceback (most recent call last):
  File "D:/Project/mvcnn-tf/train.py", line 9, in <module>
    from utils import train_utils
  File "D:\Project\mvcnn-tf\utils\train_utils.py", line 19, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'

my tensorflow version is 2.0
when my version changed 1.12.0,i faced problems like:
Traceback (most recent call last):
  File "D:/Project/mvcnn-tf/train.py", line 352, in <module>
    if tf.io.gfile.exists(FLAGS.train_logdir):#判断目录是否存在
AttributeError: module 'tensorflow._api.v1.io' has no attribute 'gfile'

i don't know how to solve,thank you

**Comment by ace19-dev** [comment]
hi, jiangyanjavawin.

maybe, there are two solution 
1. you can change tensorflow version over 1.13.0 
2. you can edit like below
 if tf.io.gfile.exists(FLAGS.train_logdir): -> if os.path.isdir(FLAGS.train_logdir)

thank for interest.
