### ISSUE TITLE
About code content

### ISSUE THREAD

**Issue by Pengzz1024** [ace19-dev/mvcnn-tf#4]
Thank you so much for sharing, but I have a problem, could you please help me solve it?
In train.py, there is " training_tf_filenames = os.path.join(FLAGS.dataset_dir, 'train.record')" what does train.record means? The name of folder? Or a list contains all the names of data inside this path?

**Comment by ace19-dev** [comment]
Hi Pengzz1024.

'train.record' means name of tfrecord file. 
you can see what tfrecord means in https://medium.com/mostly-ai/tensorflow-records-what-they-are-and-how-to-use-them-c46bc4bbb564

thank you for your interest.
